{
 "title": "Crypto_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Circulating Supply vs. Market Cap  (Top 50 where  market_cap < max(market_cap)/100)",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name, circulating_supply, market_cap \r\nFROM crypto_data\r\nWHERE circulating_supply IS NOT NULL AND market_cap IS NOT NULL\r\nand market_cap < (select max(market_cap) from crypto_data)/100\r\norder by circulating_supply\r\nlimit 50\r\n;"
    }
   ]
  },
  {
   "title": "Price Change Percentage Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT symbol, price_change_percentage_24h \r\nFROM crypto_data\r\nWHERE price_change_percentage_24h IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Top 10 Cryptocurrencies by Market Cap ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT name, market_cap \r\nFROM crypto_data\r\nORDER BY market_cap DESC \r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Market Capitalization vs. Price Change Percentage (24h) ",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT name, market_cap, price_change_percentage_24h \r\nFROM crypto_data\r\nWHERE price_change_percentage_24h IS NOT NULL\r\norder by market_cap \r\nlimit 95\r\n;"
    }
   ]
  }
 ]
}